### ISSUE TITLE
Copyright unclear

### ISSUE THREAD

**Issue by innir** [trussed-dev/delog#6]
Hi,

I'm packaging delog for Debian to be able to package solo2-cli some day. Unfortunately it is not very clear to me who the copyright holder of the code is. LICENSE-MIT states "Copyright (c) 2018 John Scarrott" but the first commit in this repository is from 2020 and it seems John Scarrott didn't commit any code. Cargo.toml lists Nicolas Stalder as author.

Could you please clarify and correct? (and also release a new version once fixed?)

Thanks!

**Comment by nickray** [comment]
I have no idea how Mr Scarrott ended up in this license file :man_facepalming:

Releasing a v0.1.5
